### ISSUE TITLE
Crash on patch initialization

### ISSUE THREAD

**Issue by eeekie128** [Synthesis-Collective/SynthEBD#1]
Hello! I am getting a crash when I attempt to run the patcher:

"SynthEBD has crashed with the following error: An object implementing IHandleObservableErrors (often a ReactiveComment or ObservableAsPropertyHelpter) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case."

I thought this may be due to windows realtime protection, but I had it disabled.
![Screenshot 2022-02-23 144755](https://user-images.githubusercontent.com/100317500/155407097-498aa49b-ecc5-4d9e-9731-33aa4fe48d33.jpg)

**Comment by Piranha91** [comment]
Thanks for the report! May I ask for some info?
- Did you have any config files installed (and if so, which ones?)
- Are you running through MO2?
- Are you running SkyrimSE?
- What is your body assignment mode, and if it's BodyGen, do you have a BodyGen config installed?
- If you remember, which settings did you change from their default values?
- Which patcher modes are checked in the main menu? (Assets / Body Shape / Height)?

Thanks!

**Comment by eeekie128** [comment]
Sure thing! 

- Yes, I had all your prepackaged config files installed, as well as a few others that I pulled from my previous zebd json files. I validated all of them (after some time fixing things). 
- Yes, I am running through MO2
- Yes, I am running Skyrim SE 1.57 (not AE)
- I have body assignments turned off, as I have the non-ostim Obody installed and it didn't seem to be recognizing it. 
- I removed beast races from the patchable races from main menu, and from inside textures and meshes, I deselected "allow config files to change NPC meshes" 
- Textures & Meshes/Apply body shapes using: None/Apply height changes

I hope this helps! Let me know if you need anything else.

**Comment by eeekie128** [comment]
For what it's worth, I deselected all my own config files and just used yours (tempered for male and female, vitruvia, bijin) and the patcher seemed to run, so it's definitely a problem with how I have one of my files set up.

**Comment by Piranha91** [comment]
Ah interesting, that makes me feel a bit better :). I just released version 0.2 which _should_ print the stack trace from the error into a text file in SynthEBD\Logs\Crash Logs. I say "should" because I just wrote that function in the last 5 minutes and I need to run to work so I can't test it! If you don't mind, can you please download and install v0.2 (no need to delete old files, just drag and drop into your SynthEBD folder and allow new files to overwrite the old ones) and try to reproduce the issue, and if it works, paste or upload the crash log .txt file here? Thanks again for taking the time to help evaluate the beta!

https://github.com/Synthesis-Collective/SynthEBD/releases/tag/v0.2.0

**Comment by eeekie128** [comment]
Whoops, I'm having trouble starting this version, but it's generating a crash log! 

[2022-02-23-17-08.txt](https://github.com/Synthesis-Collective/SynthEBD/files/8128418/2022-02-23-17-08.txt)
