### ISSUE TITLE
Patching with empty record

### ISSUE THREAD

**Issue by zhongjiedong** [Synthesis-Collective/SynthEBD#108]
![2023-03-04 10_19_34-SSEEdit 4 0 4b x64](https://user-images.githubusercontent.com/20669755/222894366-5d3a44d4-1a49-4d49-99c9-432631da21f9.jpg)

**Comment by Piranha91** [comment]
Can you link me to that mod, tell me which config files you’re using, and tell me if you’re running in Synthesis or standalone mode?

**Comment by zhongjiedong** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/72981

Running from the main Synthesis app 0.9.6.2

**Comment by Piranha91** [comment]
Weird, I'm not able to replicate this. Using the latest SynthEBD versioning, corresponds to 0.9.7.2:
![image](https://user-images.githubusercontent.com/63175798/222919045-c0f7575e-b678-4e28-b69c-7c5d6354c316.png)

Maybe try updating to latest and see if that helps? If not, I'd need to see which config files you're using to figure out why it thinks it needs to patch that record. If you launch SSEedit and let it build its referenced cache, does that cell get "referenced by" any NPC, armor, armature, or texture set? If not, I'm tempted to think it might be some sort of merge issue because as you implied there's no reason for NPC to patch that record, and nothing coded in SynthEBD that would make it look at or edit Cell records unless they're referenced by an NPC as part of a texture's "destination path"?

**Comment by zhongjiedong** [comment]
I'll give it a go on the latest build and let you know

**Comment by Piranha91** [comment]
Sounds good, let me know. I just checked in SSEedit and it doesn't seem that XMarker is Referenced By anything at all, so I have no idea how SynthEBD would be able to access it. Implies to me it's either a corrupted patcher output, some sort of manual edit, or a bug in how SSEedit is displaying the record (don't think the latter is likely).

**Comment by Piranha91** [comment]
Closed due to inactivity.
