### ISSUE TITLE
Config File for CBBE 3BA Custom Normal Maps has multiple subgroup errors reading" is invalid because it is not contained within your O/AutoBody descriptors" error

### ISSUE THREAD

**Issue by ZayAnything** [Synthesis-Collective/SynthEBD#123]
Attempting to set-up SynthEBD Mix-In config files for Custom Normals by Acro748, xs2reality and PepperoniB01 found here:
https://www.nexusmods.com/skyrimspecialedition/mods/73717?tab=files

I am using Vortex as my mod manager and BodySlide/OBody as my body manager. 

After installing the config from the archives and being sure to set up the body meshes in BodySlide - I open Vortex back up, enable the SynthEBD file that's been created in Vortex and I open SynthEBD back up. When validating the config file I just created I am seeing this [error log.](https://github.com/Synthesis-Collective/SynthEBD/files/12506532/SynthEBD_Error_CBBE.3BA.Custom.Normal.Maps.txt)

I am unsure if I'm doing something incorrect in my setup for BodySlider, or if it's something to do with the fact this config file requires 4 base pre-reqs that slightly overwrite each other - XS Sporty Sexy Map seems to be the primary offender of these overwrites according to Vortex. I am getting two "mods are redundant" notifications for two of those for pre-reqs displaying the following:

![image](https://github.com/Synthesis-Collective/SynthEBD/assets/143859917/d8d98cc7-a7ca-4cee-9036-d6b2d4e2539b)

Each one in more detail:

![image](https://github.com/Synthesis-Collective/SynthEBD/assets/143859917/af641a40-9b72-4d63-a41c-b5883941785e)

![image](https://github.com/Synthesis-Collective/SynthEBD/assets/143859917/271b1b63-23de-4454-919d-76e3ff069b36)

Even the Nexus page for this config file says it has a 10% chance of installing successfully, but I'm curious if there's some bug or something this could lead to. Unless there's a better config file for this that's available and more stable that I can use instead .

**Comment by Piranha91** [comment]
When these mods are listed as prereqs, it doesn't mean they need to be installed through vortex. You just need to follow the config installer in SynthEBD and let SynthEBD handle installation - otherwise they'll overwrite each other as Vortex is warning you about. Whichever texture mod you install through Vortex is what your own character will use (as well as any NPCs not patched by SynthEBD), and if you install multiple overlapping files such as what you're showing here, the one installed last (lowest in your mod order) will win.

Regarding the "not contained within your O/AutoBody descriptors" error, that's because pamonha (author of those config files) uses custom bodyslide rule sets that go into more detail than the default ones that ship with SynthEBD. It's the ExportedBodySlides.json file (first one in the Downloads section on the nexus page you linked) - you would import that through the bodyslides menu:

![image](https://github.com/Synthesis-Collective/SynthEBD/assets/63175798/7e4d2d9a-f8c1-4079-b5aa-aab6122a87d1)

Or, if you don't want to use his bodyslide rules, you could go into the config file you just downloaded and delete the missing rules:

![image](https://github.com/Synthesis-Collective/SynthEBD/assets/63175798/e2529853-c401-428e-a5c9-83e4189efdc1)

**Comment by ZayAnything** [comment]
Thank you for getting back to me so quickly, as well as the clarifications for those definitions I was getting incorrect. I'm not necessarily new to the mod scene but there are still a lot of technical aspects to this side of things I'm still trying to wrap my head around.

I decided against using the Custom Normal Maps for now, but these things are good to know for next time.
