### ISSUE TITLE
Sassyteendolls.esp CTD when using 1.0.2.5 but not when using 1.0.1.5

### ISSUE THREAD

**Issue by Brakker643** [Synthesis-Collective/SynthEBD#127]
[Crash_2023_12_2_11-59-25.txt](https://github.com/Synthesis-Collective/SynthEBD/files/13536351/Crash_2023_12_2_11-59-25.txt)

Hi

I'm consistently getting the CTD in the attached crash report when using SynthEBD V 1.0.2.5. It's not the particular NPC in this log but it's always a female NPC from sassyteendolls.esp. When I run v1.0.2.5 on the same load order I don't get the crash. Do you know if anything changed between the version that could be causing this?

Thanks

**Comment by Piranha91** [comment]
Hmm, I haven't used this mod and I'm not sure why one particular one would be crashing. That said, I'm not particularly proficient at diagnosing in-game crash logs but my guess is it's just saying SynthEBD is the winning override for that NPC, not necessarily that it's causing the crash. From that log I'd look into Valdacil's Item Sorting.

The only major thing that changed since 1.0.1.5 on the in-game side is how it interfaces with OBody (which does invoke skee.dll that's referenced in the crash log, so maybe there is an issue there). You can revert it to the original behavior by changing the assignment mode from Native back to Script (Script was the only option in 1.0.1.5).

![image](https://github.com/Synthesis-Collective/SynthEBD/assets/63175798/2c426138-81c1-4ac7-abd1-bc9604e09bb0)

**Comment by Brakker643** [comment]
It wasn't SynthEBD at all. It seems that it was Fertility Mode. Thx for taking your time to help!

**Comment by Brakker643** [comment]
Closed
