### ISSUE TITLE
Face textures are not assigned by neither SynthEBD or by RACE record.

### ISSUE THREAD

**Issue by SharDi0** [Synthesis-Collective/SynthEBD#129]
I keep getting this error when I try to just randomize headparts of npcs:
"Reverting headparts of NPC Kharjo (Kharjo) 01B1D2-Skyrim.esm because no face texture was assigned by SynthEBD and no default face texture exists in its RACE record."

I bet its a stupid mistake on my part but I just cant figure out why exactly it tells me that there is no face texture in race record, its a skyrim's khajiit npc, I have no mods that override it too I believe. And absolutely nothing gets outputted in the folder. 

I am using synthesis version of SynthEBD since standalone version won't let me see all plugins.

**Comment by Piranha91** [comment]
This is not an error but rather a warning about what the patcher is doing. The reason for it is a bit "in the weeds". For most types of head parts, replacing them in-game triggers the dark face bug. SynthEBD (and the original EBD) got around this by calling the EBD face update script to re-apply the NPC's patched face texture. But that fails in the case where you don't use EBD/SynthEBD to apply face textures (e.g. your case where you're only using it to apply headparts). I realized in that case that instead of refreshing with a randomized face texture, I could fall back and use the face update script with the NPC's Race's vanilla plugin:

![image](https://github.com/Synthesis-Collective/SynthEBD/assets/63175798/8a15a6b8-9ab9-497b-bd99-2cd46b2cfb1f)

However, for some reason, the Khajiit race doesn't have one:

![image](https://github.com/Synthesis-Collective/SynthEBD/assets/63175798/427dac41-a2b0-4001-878f-fd7522821535)

Hence SynthEBD telling you generically that "hey, you have an NPC who didn't get an EBD-assigned face texture, and I also don't see a default face texture in their race record, so I'm going to cancel the headpart assignment because otherwise they're going to get a dark face bug that I can't fix."

You can probably get around this by just copying the SkinHeadMaleKhajiit record from the list right above the DFTM slot into the DFTM slot, and saving that as a small espe plugin. I could probably even have SynthEBD do that automatically for Khajiit in a future update.

**Comment by SharDi0** [comment]
Thank you very much, issue is resolved.
