### ISSUE TITLE
Headparts do not get assigned.

### ISSUE THREAD

**Issue by SharDi0** [Synthesis-Collective/SynthEBD#130]
I am trying to patch khajiits with humanoid headparts, made sure to add face texture to khajiit(although there's like 3 entries in log that still say that some npcs dont have textures) and then ran the patcher in synthesis. Esp I get has nothing changed in khajiit npcs. Headparts have khajiit race as allowed race and also set alias race as nord in case some headparts don't.

**Comment by Piranha91** [comment]
Do you see a headparts .json file in your SynthEBD output?

**Comment by SharDi0** [comment]
After running standalone SynthEBD(since synthesis ignores my output folder) I've noticed it actually says that 0 npcs got patched, status log consists of just 2 entries about npcs and their tail data not being found. Output does have a HeadPartAssignements.json file.

P.S. No, headparts have all kinds of races allowed and usually remove khajiits, so there is always atleast nord allowed.

**Comment by Piranha91** [comment]
Do other non-khajiit NPCs get headparts? Can you zip up your settings files from SynthEBD\Settings (unless you're using a portable settings folder) and upload them?

**Comment by SharDi0** [comment]
No, just tried to distribute some headparts on nords and while esp does have only nords listed, none of them have for an example ks hairdo's headpart.

[Settings.zip](https://github.com/Synthesis-Collective/SynthEBD/files/13670260/Settings.zip)

**Comment by Piranha91** [comment]
Are you getting any specific warnings in the output log? For example, when I try to patch headparts without also assigning skins, I get the following warning for Bijin NPCs:

`Reverting headparts of NPC Carlotta Valentia (CarlottaValentia) 013B99-Skyrim.esm because no face texture was assigned by SynthEBD or its original plugin, but the NPC has a WNAM so SynthEBD HeadPart assignment would cause a neck seam.`

This is related to the above issue - in this case the NPC has a custom skin but no custom face texture, so SynthEBD doesn't want to patch it in case applying the default racial skin from Skyrim.esm causes a neck seam with the custom body. Are you seeing anything like this for your Khajiits?

Otherwise, I tested distributing hair from KS Hairdos Light to Khajiit NPCs and had no issue (aside from some of the hairs clipping with khajiit heads). Couple options you can try:

1) Change the distribution probability from 50% to 100%
![image](https://github.com/Synthesis-Collective/SynthEBD/assets/63175798/4d8a39a4-b9ed-46e9-b6c9-dd61e2fe15a7)

2) Disable the custom facegen filter
![image](https://github.com/Synthesis-Collective/SynthEBD/assets/63175798/5e3a3f65-9326-4d16-90e0-b3fb0cb17890)

3) Make sure you added a default facetexture to khajiit NPCs and are no longer getting the headpart reversion message as per your OP. I just pushed an update to the Synthesis version of the patcher that handles this automatically for Khajiit and Argonian NPCs, but I'm not ready to release a new standalone version yet.

**Comment by SharDi0** [comment]
Thanks, I think I got it working properly.
