### ISSUE TITLE
so i use jBS2BG to convert my bodyslides to bodygen morph format..

### ISSUE THREAD

**Issue by apotekakademi** [Synthesis-Collective/SynthEBD#14]
how do i convert the generated template files. 

format:
PRESET_NAME=slidername1@0.0to1.0, slidername2...

is there no built in way to convert jBS2BG generated stuffs? I have 50 different bodyslide that i converted to this format seems kinda tedious to do.

**Comment by Piranha91** [comment]
Whoops! I had this functionality in zEBD - thought I implemented it in SynthEBD as well but looks like I forgot. I can add it in the next update tonight or tomorrow. If you need it faster and are familiar with zEBD, you can launch that, use the "Import a BodyGen  Morphs INI File" button, save the resulting BodyGen config, and load that into SynthEBD by placing the .json into the SynthEBD\BodyGen Configurations folder. Otherwise I will include in SynthEBD soon.

**Comment by apotekakademi** [comment]
> Otherwise I will include in SynthEBD soon.

i dont mind waiting!
thanks for replying so quickly. ill do that for now.

**Comment by Piranha91** [comment]
Functions added in 0.7.1.
- Import templates.ini is in the BodyGen Integration menu -> Morph List -> bottom of the list -> Import Templates.ini
- Import morphs.ini is in the Specific NPC Assignments menu -> bottom of the NPC list -> Import BodyGen Morphs.ini (General Settings -> Apply Body Shapes Using must be set to `BodyGen`).

Thanks for pointing out the omission.
