### ISSUE TITLE
Khajiit ＆ Argonian texture destination

### ISSUE THREAD

**Issue by Daikichi-Takahey** [Synthesis-Collective/SynthEBD#17]
Are Khajiit and Argonian working well ?
I tasted https://github.com/CramMods/SynthEBDAssetPacks/releases/tag/1.0.5 & ZEBD config from NEXUS
            

![スクリーンショット (38)](https://user-images.githubusercontent.com/100354903/171541779-e8652388-cd58-474c-9c75-43026e45b52e.png)
![スクリーンショット (40)](https://user-images.githubusercontent.com/100354903/171542109-ef77666c-3ad1-4aae-be6e-24f32b648a3b.png)

**Comment by Piranha91** [comment]
Ah interesting. I checked the Masculine Khajiit textures and it looks like the record template was set incorrectly: 
![image](https://user-images.githubusercontent.com/63175798/171560346-3833cec8-dabc-4164-bb3c-53ef9ac70ba3.png)
This should be KhajiitMale, not KhajiitFemale. Additionally, if you are using EasyNPC, I recommend opening the config file in a text editor and replacing `PatchableRaces.Contains(Race)` with `MatchRace(Race, AdditionalRaces, MatchDefault)`. 

After doing the above, the textures seem to be assigned correctly in my testing, BUT the UI still provides red borders. This is due to an oversight on my part - I was testing Khajiit and Argonian with Tempered Skins, and the UI backend recognizes that Khajiit are not covered by the "default" record template and switches over. In this case, the entire config file is for khajiit so the UI gets confused and looks in the default template, which is for humanoids. Again, the patcher itself executes correctly; it's just the UI that gets tricked. I'll fix this in the next version. Thanks for the heads up.

**Comment by Piranha91** [comment]
Fixed in 0.7.5. Sorry for the very delayed heads up.
