### ISSUE TITLE
BodySlide randomization running two times per NPC

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#78]
Hey Piranha, it's me again 🤣 

This time I'm fiddling with the MixIn option, trying to understand how it works. I've setup a separate config file to distribute some textures which are missing from some of the other main asset packs. 

So, first, it seems that patcher runs are taking a much longer time, and after checking the logs, I noticed that the BodySlide Randomization is running twice... once after Main Asset pack assignment (which actually have rules for BodySlide selection) and another after MixIn assignment (which have no Bodyslide rules). Shouldn't Bodyslide selection run only once per NPC?

And second, according to documentation MixIn is designed to supercede the main asset pack in case of texture overlap. Would it be possible to add a feature so that default behaviour would be not to overlap, and have MixIn only patch those textures which aren't already assigned by Main Asset pack assignment? I think this would come in handy in assigning the occasional missing texture of an asset pack.

**Comment by Piranha91** [comment]
I’ll check the bodyslide issue; it should be receiving the already assigned bodyslide rather than running again. Could you upload your mixin file so I know I’m testing in the right environment?

I’m planning on building a UI ordering feature where you can select which order mix ins are assigned relative to primary and each other. I think it’ll have to be in the release after next though. That circular dependency bug you reported turned out to be a tougher nut to crack than I anticipated - think I’m going to try to get that fixed and then release 0.9.

**Comment by leonardovcr** [comment]
Sure, it's just a plain proof of concept to understand how it works:

[Test.zip](https://github.com/Synthesis-Collective/SynthEBD/files/10407963/Test.zip)

It assigns a black subsurface texture for everyone. The texture is from your ALT2 asset pack.

**Comment by Piranha91** [comment]
Forgot to mention, 0.9.1.2 should fix this issue. Working on your other bugs/requests for 0.9.1.3.

**Comment by leonardovcr** [comment]
Thanks Piranha, it's fixed now, closing issue...
