### ISSUE TITLE
Suggestions for MixIn assignments

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#85]
Hey Piranha, I'll leave these suggestions as a separate issue for better organization, a reminder, and because I think they would offer great flexibility to modding in a next release:

 - Allow a global probability assignment for MixIn asset packs (something akin to the current 'distribution probability' we already have on head parts distribution).
 - Allow priority assignment between MixIn and Primary asset packs.

These would be useful to distribute textures in order to 'fill-in' missing textures from other asset packs. For example, HeadDetail textures or those 3BA etc textures which some skin mods do provide, but others don't.
This way it would be possible to create a MixIn pack of all those 3BA textures from the 3BA mod, and assign them as a complete fill-in or complement to compatible packs that lack all those textures, or who just provide the diffuse. This should be useful for providing missing HeadDetail textures to other asset packs too.

Thanks!

**Comment by Piranha91** [comment]
Added priority assignment in 0.9.1. 

For the global probability assignment, do you mean something like for Headpart categories that controls a yes/no "will this mix-in get assigned, even if the target NPC fully complies with its distribution rules"?

**Comment by leonardovcr** [comment]
Something like that, yes. HeadParts have this option for distribution probability:

![image](https://user-images.githubusercontent.com/13605450/214332423-be769771-69b0-4ad5-8778-e73687700bab.png)

In my mind, for MixIn, the behaviour would be something like this:

 - if there is no currently assigned texture for that npc, and for that texture type, let MixIn fill-in (this could be done with a lower priority assignment for MixIn, I think)
 - if the target npc fully complies AND already has assigned textures for those texture types AND MixIn is set to a higher priority, then MixIn would supercede based on an arbitrary probability.

The first one would be useful to distribute 3ba _etc textures for those asset packs that doesn't provide them, by letting MixIn have a lower priority (filling in first), and then letting Primary Asset Pack provide the rest (even superceding any conflicting textures, since Primary may provide textures better suited for).

The second one would be useful to distribute those mods which only provide standalone normal textures. This way one could have the option to assign them to all Primary Asset Packs without having to customise and add them to each Primary Asset config rules.

**Comment by Piranha91** [comment]
Ok. The priority is already able to be set - if a mix-in comes first and a primary comes second and they both hit the same destination path, the primary will win. If a mix-in comes after primary in the assignment order, the mix-in will win. I can add in a global distribution probability for mix-ins similar to headparts.

**Comment by Piranha91** [comment]
Alright, in version 0.9.1.2, the probability in the whole-config distribution rules for a Mix-In is now a percentage that dictates the probability that the given Mix-In will get assigned. Let me know how it works for you.

**Comment by leonardovcr** [comment]
Hey, testing it know with Primary Asset packs followed by one Mix-In with only custom normal maps.

There's just something which I didn't quite understand yet. During Mix-In assignment, some normal maps are excluded with this message:

"is invalid because its allowed descriptors do not include any of those annotated in the descriptors of assigned preset"

So, when deciding the Mix In assignment, the patcher compares the custom normal maps body descriptors with those that resulted from the Primary Asset pack rules, or from the previously selected Bodyslide?

**Comment by Piranha91** [comment]
Should be the bodyslide. In the asset ordering menu, "primary" and "body shape" are linked and assigned at the same time (this is so that the patcher can execute its "meta loop", for lack of a better term - it assigned a valid combo, tries to assign a body shape, and if no shape can be assigned, backtracks and tries another valid combo, until all combinations + body shapes are exhausted. This could get really expensive, and obnoxious to code, if it had to backtrack through mix-ins as well, so it only does the "meta loop" for primary packs). 

For mix-ins, the way it should work is as follows:
- If a mix-in is assigned before primary/body shape, then the patcher treats its body shape descriptors as law and tries to force a body shape that complies with them (as well as with the primary).
- If a mix-in is assigned after primary/body shape, then it must respect the descriptors from the already-assigned body shape (e.g. if its descriptors disallow the already-assigned body shape, then it's the mix-in, rather than the body shape, which gets rejected).

At least that's how it's supposed to work - I've been a bit bandwidth-limited recently so if that's not consistent with what you see, let me know.

**Comment by leonardovcr** [comment]
Hummm thanks for explaining... however, just to clarify,  and to check if the logic seems ok... I think I'm not following SynthEBD's logic for bodyslides...

I have the following Body Normal, with these descriptors:

![image](https://user-images.githubusercontent.com/13605450/215286041-51219a3e-11f1-47bb-8adf-04acb3b99bda.png)

What is the resulting boolean logic here which SynthEBD considers? 

 - Allow only bodyslides which are tagged with build ('average' OR 'slim' OR 'curvy' OR 'chubby') AND chest ('small' OR 'medium' OR 'big')?
 - Allow only bodyslides  which are tagged with build ('average' AND 'slim' AND 'curvy' AND 'chubby') OR chest ('small' AND 'medium' AND 'big')?

I built the rules with the first logic in mind, but I suspect SynthEBD applies the second one. I'm trying to understand that better because, running the patcher with those rules from the screenshot, the patcher chose for that body normal, a bodyslide with these descriptors:

![image](https://user-images.githubusercontent.com/13605450/215286527-eff41ff3-4138-45d9-8ed4-59e97adeffbe.png)

Which shouldn't have happened, since the body normal is not intended for a 'fit' body.

Later on, when processing the following Mix-In with custom normal maps, the patcher assigned one with these descriptors:

![image](https://user-images.githubusercontent.com/13605450/215286827-b758969b-1ad8-4e7e-8372-c2c7448ff56d.png)

Which implies it followed the logic from the Primary Asset pack (which IMO should be the intended behaviour) and not from the Bodyslide (as you explained)... 🤔

**Comment by Piranha91** [comment]
To clarify, the first screenshot is the bodyslide descriptors of the primary asset pack? If so, something is going wrong with the bodyslide assignment - it's the first logic which should be implemented (match build AND match chest). Can you upload the verbose log for that NPC?

The mix-in logic is "correct" in the sense that, if the patcher is working properly, the assigned bodyslide complies with the Primary descriptors, which means that if the mix-in complies with the bodyslide, then it also complies with the primary.

**Comment by leonardovcr** [comment]
Here's the log:

[Bandit Cryomancer (EncBanditIce06HighElfF) 0010D7-OBIS SE.esp.xml.zip](https://github.com/Synthesis-Collective/SynthEBD/files/10528121/Bandit.Cryomancer.EncBanditIce06HighElfF.0010D7-OBIS.SE.esp.xml.zip)

Just disregard that report of the mix-in running after. It seems to have behaved correctly, and did not assign a wrong normal. I got confused looking at two logs at once 😞 

And yeah the first pic is from the normal map of the primary asset pack.

A way to export bodyslide annotations would be useful indeed, maybe something similar to what is already done with race groupings and attribute groups.

On another note, I think I'm also running into patcher or/and logic issues when creating an attribute group (for example, female mature) and adding multiple groups (e.g. female age 40, female age 50)... I'll investigate a bit more and report on another issue then...

**Comment by leonardovcr** [comment]
Here are the annotations used for primary asset pack:

![image](https://user-images.githubusercontent.com/13605450/215287963-c9dd5b60-f69b-4918-80c9-c1cd7eb1979c.png)

And for the bodyslide selected by the patcher:

![image](https://user-images.githubusercontent.com/13605450/215288030-511a23ed-bb04-4411-b942-ca822f2c91e6.png)

**Comment by Piranha91** [comment]
Hmm... let me improve the verbose logging a bit and make a new release in just a bit - it won't fix the issue but might make it a bit easier to diagnose for the next one. Btw, I noticed that for assets there are log entries like:

```
Subgroup BN.CBBE3BA.Musc (Muscles)  is invalid because the NPC matches one of its disallowed attributes: 
{Group: [Cannot be Muscular]}
```

But for bodyslides there are ones that are like:

```
Preset Warrior Princess 3BA is invalid because the rules for its descriptor Age: Younger is invalid because the NPC matches one of its disallowed attributes: 
{Group: []}
```

Do you have an unnamed attribute groups in your general settings, or is this a bug?

**Comment by leonardovcr** [comment]
First one is fine, it's a list of npcs which shouldn't get muscular body normals. The second one however, looks like a left over bug. 

Checking now, there is an allowed npc attribute rule there, with a force if, which used to have an attribute group (inherited from general settings) which I have recently renamed or deleted, can't remember which... it looks like after an app restart, the group was gone from the rule, but the rule remained there, empty..... weird...

**Comment by Piranha91** [comment]
Whoops. I was baffled how this was happening because I spent hours upon hours validating the algorithm - turned out I broke it in 0.9.1 when introducing the Asset Ordering feature - the descriptor rules going to the bodyslide selector were specifically missing those from the Primary asset pack, and only passing the mix-ins. Thank you for catching this.

**Comment by leonardovcr** [comment]
That new validator is quite useful, it caught a lot of blank attr groups across many asset packs now, thanks!

The new verbose logging is great too, very detailed, thanks. However, I fear the problem is not solved yet... here are some log samples for multiple NPCs (no mix-ins involved on these):

**NPC1 (no mix-in):**
Applied descriptor rules: 
BFN.4K.U.S.D: Allowed Descriptors: Build: [Slim, Curvy] | Chest: [Small, Medium, Big]
...
Chose BodySlide Preset: Athletica						
Contained descriptors: 
Build: [Fit, Muscular]
Chest: [Small]



**NPC2 (no mix-in):**
Applied descriptor rules: 
BN.M.D: Allowed Descriptors: Build: [Average, Slim, Curvy, Chubby] | Chest: [Big, Huge]
...
Chose BodySlide Preset: Moderate Curvy
Contained descriptors: 
Build: [Average, Slim]
Chest: [Flat]



**NPC3 (no mix-in):**
Applied descriptor rules: 
BN.Crv.Smo: Allowed Descriptors: Build: [Average, Slim, Curvy] | Chest: [Big, Huge]
...
Chose BodySlide Preset: CBBE-3BBB The Sensual Lady_By Bacetrica
Contained descriptors: 
Build: [Average, Curvy]
Chest: [Medium]



**NPC4 (mix-in seems to have matched primary asset descriptor rules, but primary and bodyslide didn't):**
Applied descriptor rules: 
BN.D.NH: Allowed Descriptors: Build: [Slim, Curvy, Fit] | Chest: [Small, Medium, Big]
...
Chose BodySlide Preset: 3BA One Body
Contained descriptors: 
Build: [Average]
Chest: [Big]
...
Successfully generated combination: CBBE 3BA Custom Normal Maps:HN.CBBE3BA.Def|BN.CBBE3BA.NipTh|HaN.CBBE3BA.Def
Applied descriptor rules: 
BN.CBBE3BA.NipTh: Allowed Descriptors: Build: [Average, Slim, Curvy] | Chest: [Medium, Big, Huge]


**NPC5 (no mix-in):**
Applied descriptor rules:
BN.M.S: Allowed Descriptors: Build: [Average, Slim, Curvy, Chubby] | Chest: [Small, Medium]
...
Chose BodySlide Preset: Full Apex Girl Growth
Contained descriptors: 
Build: [Average, Fit, Muscular]
Chest: [Big]

**NPC6 (this one seems ok, matching all three descriptors from primary, mix-in, and bodyslide):**
Applied descriptor rules: 
BN.M.D: Allowed Descriptors: Build: [Average, Slim, Curvy, Chubby] | Chest: [Big, Huge]
...
Chose BodySlide Preset: Creamy Curves	
Contained descriptors: 
Build: [Curvy, Fit, Muscular]
Chest: [Big]
...
Applied descriptor rules: 
BN.3BA.PNBBSB: Allowed Descriptors: Build: [Average, Slim, Curvy, Chubby] | Chest: [Medium, Big, Huge]


I wonder how convoluted the code may be getting now... making bugs hard to spot :(

Regarding all these possible combinations of primary asset and mix-ins, don't you think a simpler and better strategy would be to let the bodyslide selector run only at the end of primary asset and mix-in(s) combinations, letting the last body descriptor rules win, following the user defined Distribution Order? I mean, something like:

 - run a mix-in pack (if any) and save its descriptor (if any)
 - run a primary asset pack and save is descriptor
   - at this point, patcher should try to merge both descriptors, but if any incompatibility is found, disregard the previous one and keep the current
 - run next mix-in (if any) and follow the same logic before, as in, try to merge previous descriptors with current one, and if any incompatibility is found, disregard the last and save the current
 - finally, after all mix-ins are processed, run the bodyslide selector

For example:

1st   MixIn:               Build: [Average, Curvy, Chubby] | Chest: [Medium, Big]
2nd Primary Asset:   Build: [Average, Chubby] | Chest: [Big] | Race: [Nord]
 - Here we have a new "Race" descriptor, so we try to inherit that:
Combining both:      Build: [Average, Chubby] | Chest: [Big] | Race: [Nord]
3rd MixIn:                 Build: [Average] | Chest: [Medium, Big] |
Final combination:   Build: [Average] | Chest: [Big] | Race: [Nord]
Finally, run bodyslide selector based on final combination

Another example:

1st   MixIn:               Build: [Average, Curvy, Chubby] | Chest: [Medium, Big]
2nd Primary Asset:   Build: [Muscular, Fit | Chest: [Big, Huge] | Race: [Nord]
 - This time we have conflicting rules, so, we prioritize the last asset pack from the distribution order:
Combining both:      Build: [Muscular, Fit] | Chest: [Big] | Race: [Nord]
3rd MixIn:                 Build: [Average] | Chest: [Medium, Big] | Race: [Breton]
 - Again, some conflicting rules. Prioritizing the last asset pack from the distribution order:
Final combination:   Build: [Average] | Chest: [Big] | Race: [Breton]

What do you think? Does that makes sense?

**Comment by Piranha91** [comment]
I'd be reluctant to make that change for a couple reasons

1) The "main product" of SynthEBD is the primary asset pack. The way the algorithm works now gives priority to to making sure the primary asset pack works with the assigned body shape by backtracking and selecting a new primary if the current one can't be made to work with any body shapes. If I separate them out, it adds additional complexity. What happens if no valid body shape can be assigned at the end? Does the patcher backtrack through everything and try to find an alternate combination at every point? What happens if, for a given mix-in, the descriptor rules are completely incompatible with the selected bodyslide? Should the mix-in be removed (e.g. "declined"), or should the patcher throw its hands up and choose a bodyslide irrespective of descriptors? The way it is now gives a lot of flexiblity - if the user wants to prioritize primary, they put it first and then all mix-ins have to comply with those descriptors. If mix-ins have descriptors that need to be prioritized, they go in the assignment order before primary/body shape. I think this is the most customizable way to do it, and...

2) It works in my testing. I made verbose logs for about 10-15 NPCs, and each of them are getting bodyslide assignments that are consistent with their primary asset descriptors. In your cases above, are you sure they were generated with the latest SynthEBD? If so, could you upload some of the full logs so I can take a look at what's going on? 

3) If there's a burning need to change it I might come back and do it, but I've been burning out on SynthEBD for a while and at this point I really want to just get a working version published to the nexus, take a break, and remember some of my other hobbies. I've mentioned this before on Discord so apologies if I sound like a broken record but for the last 4 months I've had two jobs, so it feels like I go from job #1 to job #2 to coding SynthEBD in the evening with no rest, and it's kind of burning me out. At the same time I know that at least one person is coding an at-runtime texture patcher (probably less customizable than SynthEBD but perhaps easier to install), and I'm already "competing" (if that's the right word) with RBT, so I want to get this out before it completely loses relevance. That's the main reason I'm reluctant to change the core algorithm - I'd rather just do whatever needs to be done to patch the current one and make it work as well as possible, and release.

**Comment by leonardovcr** [comment]
Yeah, nobody wants to feel burnt out, I can totally relate to that... even less so on a hobby which should actualy improve our mood instead of drain it... Working two jobs is also a pretty taxing thing :( 
Really hoping here that things work out for you IRL :)

The way SynthEBD is today already gives us a tremendous amount of flexibility, I don't think those other mods could even compare to SynthEBD 👍 

So, yeah let's try to iron out current bugs first and get this release out asap so you can take a break. I promise I'll stop being such a heavy feature requester 🤣  You've already accomodated a lot of my requests, even though those which are just quality of life and quite superfluous, and for that I'm grateful :)

Unfortunately, I've already deleted my log folder since it was growing bigger and bigger, but I did manage to luckily save a full log for one NPC here:

[Ahlam _ Ahlam _ 013BBE_Skyrim.esm.xml.zip](https://github.com/Synthesis-Collective/SynthEBD/files/10531872/Ahlam._.Ahlam._.013BBE_Skyrim.esm.xml.zip)

The Bodyslide entries are these:

![image](https://user-images.githubusercontent.com/13605450/215380134-01e35ac9-f226-4fc6-82e9-c2bad6c58e71.png)

![image](https://user-images.githubusercontent.com/13605450/215380113-7c73f046-58b7-43cf-9f5e-4af903b27ccf.png)


And yeah, I just double checked my MO2 executable and it is calling SynthEBD 0.9.2 (humm, waybe a way to check the app version from the main menu could help).

I'll leave the patcher running again tonight for some new logs, and also do some more investigating on my side.

Take care!

**Comment by leonardovcr** [comment]
By the way... now that I've posted those bodyslide pics... I've realised that maybe the patcher is correctly assigning the bodyslide, but actually printing the descriptors of the OTHER bodyslide which have the same name? 🤔

**Comment by Piranha91** [comment]
That actually seems quite possible. I wrote some code this evening to try to deconvolve that. I'm almost done with the BodySlide Annotation Exchange - just need to write the UI and test it a bit. Once that's done I'll make a new release, and we'll see if your hypothesis is correct :)

**Comment by Piranha91** [comment]
0.9.3 should be able to distinguish between BodySlide duplicates. Mind taking a look at the patch log and seeing if the issue persists?

**Comment by leonardovcr** [comment]
Humm, now I get a bunch of errors telling me to rename all my duplicated bodyslides... this will take a while...

**Comment by Piranha91** [comment]
Yeah unfortunately that's the only way to track them individually. If it helps, I could write a quick function to auto-rename duplicates.

**Comment by leonardovcr** [comment]
Thanks Piranha that would come in handy.. I've got dozens of bodyslides here. I did try to come up with a quick script here at work, but json parse eludes me...

**Comment by Piranha91** [comment]
0.9.3.1 is out, automatically renamed duplicates (but does not address your specific NPC assignments issue).

**Comment by Piranha91** [comment]
I see the problem; you were pretty close. The issue is with "category forgiveness". The way I originally intended matching to work was, if you have an asset set which assigns Allowed Descriptors:
```
{ 
   hips: [wide],
   belly: [narrow]
}
```
and a candidate bodyslide was only tagged with 
```
{
   hips: narrow
}
```

the patcher was supposed to "forgive" the missing "belly" category and consider the bodyslide matched, with the assumption that if the user cared about matching the belly they would have annotated the bodyslide with it. I made a mistake in the algorithm which resulted in the OR logic that you're seeing, where the second category would be forgiven even if the bodyslide DID have it and it didn't match. I fixed that, but then I figured that might not be the way people want the patcher to run (in fact, I'm not sure it's how I would want the patcher to run now). I think I'd rather be more thorough with the annotations and make the patcher match each category, and reject the bodyslide if it's missing that category. 

Tomorrow I'll expose a UI setting that lets the user toggle between which behavior they want for Allowed Descriptors (Disallowed will continue to reject a bodyslide if ANY category has a match). Which behavior do you think should be default for Allowed? I'm thinking "match all categories" rather than the originally intended "match same categories". Thoughts?

**Comment by leonardovcr** [comment]
Hummm, makes sense now! I've always struggled to understand the patcher logic for bodyslides, since it always seemed to not behave as I wanted...

So, now that the OR bug is fixed, I think your first assumption is reasonable, and given the default Category recommendations SynthEBD ships with (Build/Chest), same categories matching should be kept as default. I think it's useful to keep category forgiveness for those categories which are not explicitly annotated on an asset pack's allowed rules. My assumption here is to not hinder the user who has bodyslides with a lot of categories set, and is trying to annotate a very simple asset pack.

Let's say a user has all bodyslides annotated with BUILD, CHEST and AGE categories for example. He than has an asset pack with textures for build and chest varieties, but not for age (like young/mature normals). It would only be needed to annotate the textures with allowed build and chest categories, and let the patcher accept any age category. Now, for asset packs that also comes with young/mature normals, the user would then add age category on allowed descriptors for those.

Oh, and everything I said is considering category matching only. After this initial matching, categories **values** should still be processed with OR operators regardless, imho. Since many bodyslide shapes may be eligible for one or more normals, this allows bodyslides with two values (say, fit and slim) to match any texture annotated with fit or slim.

The whole matter here is that the user has all the freedom to choose how to organize categories and values. So, in the end the best solution here imho, would indeed be a toggle to let the user choose how the logic behaves (match all/match same)...

**Comment by Piranha91** [comment]
Oh that’s an interesting point. The way I started coding it yesterday has the toggles living in the OBody misc menu and affecting all asset packs, but you think each asset pack should be able to set those toggles for itself?

**Comment by leonardovcr** [comment]
Ahhhh I'm sorry, I misunderstood the directions! Now I agree with you! If a subgroup has an allowed descriptor which the bodyslide lacks, then sure, default behaviour should be to NOT consider that bodyslide. Sorry for the confusion. If need be, the user should toggle the alternate behaviour.

Even though I'm usually prone to more flexibility (which a toggle for each asset pack allows), I fear it may lead to some confusion and code complexity. I think that, for now, it's better to follow the strategy of one global rule behaviour set for bodyslide matching in the obody misc menu.

**Comment by Piranha91** [comment]
I believe this should now be fixed in 0.9.4. Please let me know if it's still not behaving as expected - it seems like you have a more richly annotated set of bodyslides to test with than I do. 

On a related note, can I ask which version of Skyrim you're using. I updated to AE 1.6.640 a few weeks ago and everything seemed to run fine, but all of a sudden I'm finding that something about SynthEBD's bodyslide scripts is causing CTD on load (both with OBodyNG  and AutoBody in JSON mode; AutoBody in ini mode loads fine). I backtracked to a previous version of SynthEBD and it was still fine (and 0.9.4 didn't touch any of the SynthEBD script files at all) so I think something changed on my end and I didn't notice, but I can't put my finger on what it is yet. Anyway, curious how you're running it and if you have any issues.

**Comment by leonardovcr** [comment]
Thanks Piranha, will try to test this weekend. I’m on 1.6.640 with a new save since october I think… havent had any crashes related to bodyslides or autobody/obody. I did made the switch from autobody do obodyng, and from .ini to.json back in… december I think, also without any issues. Are you on latest ObodyNG? I remember reading somewhere that the author claimed to have done some changes to its json format. Maybe that could be an issue? I’m still on an earlier obodyng version for fear of incompatibilities with synthebd generated json.

**Comment by Piranha91** [comment]
Thanks! I actually realized what the problem was and deleted thinking you hadn’t read my post yet - as usual it was me being dumb - somehow my RaceMenu AE mod got dragged above my original RaceMenu SE in MO2. No crash once I disabled the SE version in favor of the correct one. Btw I think I’m on the latest version of OBodyNG - I’ll take a closer look tomorrow but I didn’t notice any issue with BodySlide distribution. The function SynthEBD calls is the same in both the original OBody and NG; any changes to the json format are handled internally by OBody. SynthEBD just tells it the name of the bodyslide to apply to a given NPC.

**Comment by leonardovcr** [comment]
Oh, no apologies needed, I was just worried if it wouldn't be too much of a coding hassle for little benefit, but the more flexibility the better :)

Finally had some time to test it today, and I think we can finally close this issue 👍  I've been checking logs for many npcs, and everything seems to be matching really fine now, great job!

However, I've now found some problems related to specific npc assignments, which I'll report on another issue to not clutter this one. 

Thanks!
